services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=meli_pass
    ports:
      - '3306:3306'
    volumes:
      - ./docs/db/melifresh_db.sql:/docker-entrypoint-initdb.d/script.sql
      - ./docs/db/melifresh_db_puchase_order_test.sql:/docker-entrypoint-initdb.d/script_purchase_order_test.sql
      - ./docs/db/melifresh_db_buyer_test.sql:/docker-entrypoint-initdb.d/script_buyer_test.sql
    healthcheck:
      test: ["CMD", "mysqladmin" , "-p$$MYSQL_ROOT_PASSWORD" ,"ping", "-h", "localhost"]
      timeout: 15s
      retries: 5
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api
    working_dir: /meli-api
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_SPRINT_URI: "mysql:3306"
    ports:
      - '8080:8080'
    volumes:
      - .:/meli-api
      - /go/pkg/mod:/go/pkg/mod
    command: sh -c "air -c .air.toml"