# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: Cache dependencies
      uses: actions/cache@v4.2.0
      with:
        path: |
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mod-


    - name: Run tests with coverage
      run: |
        go test -v -coverprofile=coverage.out ./... 
          

    - name: Display test coverage
      run: |
        go tool cover -func=coverage.out

    - name: Generate HTML coverage report
      run: |
        go tool cover -html=coverage.out -o coverage.html


    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.html
